# YOLO11n model configuration for cell detection
model: yolo11n.pt
data: datasets/cell_detection.yaml
epochs: 100
batch_size: 16
img_size: 1024
device: 0
patience: 100
save_period: 10
cache: true
workers: 8
project: training_results
name: cell_detection_yolo11n
description: Cell detection training with YOLO11n 