# YOLO11l model configuration for cell detection
model: yolo11l.pt
data: datasets/cell_detection.yaml
epochs: 100
batch_size: 6
img_size: 1024
device: 0
patience: 20
save_period: 10
cache: true
workers: 8
project: training_results
name: cell_detection_yolo11l
description: Cell detection training with YOLO11l 