# YOLOv8s model configuration for cell detection
model: yolov8s.pt
data: datasets/cell_detection.yaml
epochs: 100
batch_size: 12
img_size: 1024
device: 0
patience: 20
save_period: 10
cache: true
workers: 8
project: training_results
name: cell_detection_yolov8s
description: Cell detection training with YOLOv8s 